// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameAdminRole = "admin_role"

// AdminRole mapped from table <admin_role>
type AdminRole struct {
	ID        string    `gorm:"column:id;primaryKey;default:2683aeba-1ef0-41a0-af43-2263772b69c7" json:"id"`
	AdminID   string    `gorm:"column:admin_id" json:"admin_id"`
	AccessID  string    `gorm:"column:access_id" json:"access_id"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
	Deleted   bool      `gorm:"column:deleted;not null" json:"deleted"`
}

// TableName AdminRole's table name
func (*AdminRole) TableName() string {
	return TableNameAdminRole
}
